name: Deploy Sanity
on:
  push:
    branches: [fix/workflow]
jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v3
      - uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: . deploy
